/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpeedRouteImport } from './routes/api/speed'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as PSplatRouteImport } from './routes/p.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedRoute = ApiSpeedRouteImport.update({
  id: '/api/speed',
  path: '/api/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/speed': typeof ApiSpeedRoute
  '/api/ws': typeof ApiWsRoute
  '/p/$': typeof PSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/speed': typeof ApiSpeedRoute
  '/api/ws': typeof ApiWsRoute
  '/p/$': typeof PSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/speed': typeof ApiSpeedRoute
  '/api/ws': typeof ApiWsRoute
  '/p/$': typeof PSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/speed' | '/api/ws' | '/p/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/speed' | '/api/ws' | '/p/$'
  id: '__root__' | '/' | '/api/speed' | '/api/ws' | '/p/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSpeedRoute: typeof ApiSpeedRoute
  ApiWsRoute: typeof ApiWsRoute
  PSplatRoute: typeof PSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speed': {
      id: '/api/speed'
      path: '/api/speed'
      fullPath: '/api/speed'
      preLoaderRoute: typeof ApiSpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSpeedRoute: ApiSpeedRoute,
  ApiWsRoute: ApiWsRoute,
  PSplatRoute: PSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
